(require 'funcs)
(require 'ui)
(require 'init-multistate)
(require 'init-general)
(require 'init-which-key)
(require 'init-keybindings)
(require 'init-helm)
;; (require 'init-ido)
(require 'init-company)
(require 'init-util)
(require 'init-magit)
(require 'init-projectile)
(require 'init-neotree)
(require 'init-telephone-line)
(require 'init-elisp-mode)
(require 'init-cc-mode)
(require 'init-python-mode)

(provide 'config)
